image: node:12

stages:
  - build
  - test
  - deploy
  - deployment tests
  - cache

update cache:
  only:
    - schedules
  stage: cache
  script: 
    - npm install
    - npm install -g gatsby-cli
  cache: 
    key: ${CI_COMMIT_REF_SLUG}
    policy: push
    paths:
      - node_modules/

cache:
  key: ${CI_COMMIT_REF_SLUG}
  policy: pull
  paths:
    - node_modules/

build website:
  except:
    - schedules
  stage: build
  script:
    - echo $CI_COMMIT_SHORT_SHA
    - gatsby build
    - sed -i "s/%%VERSION%%/$CI_COMMIT_SHORT_SHA/" ./public/index.html
  artifacts:
    paths:
      - ./public

test artifact:
  except:
    - schedules
  image: alpine
  stage: test
  cache: {}
  script:
    - grep -q "Gatsby" ./public/index.html

test website:
  except:
    - schedules
  stage: test
  script:
    - gatsby serve &
    - sleep 3
    - curl "http://localhost:9000" | tac | tac | grep -q "Gatsby"

deploy to surge: 
  except:
    - schedules
  stage: deploy
  cache: {}
  script:
    - npm install --global surge
    - surge --project ./public --domain michaelbruceallen.surge.sh

test deployment:
  except:
    - schedules
  image: alpine
  stage: deployment tests
  cache: {}
  script:
    - apk add --no-cache curl
    - curl -s "https://michaelbruceallen.surge.sh" | grep -q "Hi people"
    - curl -s "https://michaelbruceallen.surge.sh" | grep -q "$CI_COMMIT_SHORT_SHA"
