image: node

stages:
  - build
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build website:
  stage: build
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
  artifacts:
    paths:
      - public


test artifact:
  image: alpine
  stage: test
  script:
    - grep -q "Gatsby" ./public/index.html

deploy to surge:
  stage: deploy
  script:
    - npm install --global surge
    - surge --project ./public --domain michaelbruceallen.surge.sh
    - sleep 3 
    - curl "michaelbruceallen.surge.sh" | tac | tac | grep -q "Gatsby"
