image: node:12

stages:
  - cache
  - build
  - deploy staging
  - test
  - deploy production
  - production tests

variables:
  STAGING_DOMAIN: staging-michaelbruceallen.surge.sh
  PRODUCTION_DOMAIN: michaelbruceallen.surge.sh

update cache:
  only:
    - schedules
  stage: cache
  script: 
    - npm install
  cache: 
    key: ${CI_COMMIT_REF_SLUG}
    policy: push
    paths:
      - node_modules/

cache:
  key: ${CI_COMMIT_REF_SLUG}
  policy: pull
  paths:
    - node_modules/

build website:
  except:
    - schedules
  stage: build
  script:
    - echo $CI_COMMIT_SHORT_SHA
    - npm install -g gatsby-cli
    - gatsby build
    - sed -i "s/%%VERSION%%/$CI_COMMIT_SHORT_SHA/" ./public/index.html
  artifacts:
    paths:
      - ./public

test artifact:
  except:
    - schedules
  image: alpine
  stage: test
  cache: {}
  script:
    - grep -q "Gatsby" ./public/index.html

test website:
  except:
    - schedules
  stage: test
  script:
    - npm install -g gatsby-cli
    - gatsby serve &
    - sleep 3
    - curl "http://localhost:9000" | tac | tac | grep -q "Gatsby"

deploy staging: 
  stage: deploy staging
  cache: {}
  except:
    - schedules
  environment:
    name: staging
    url: http://$STAGING_DOMAIN
  script:
    - npm install --global surge
    - surge --project ./public --domain $STAGING_DOMAIN

deploy production: 
  stage: deploy production
  cache: {}
  when: manual
  only:
    - master
  allow_failure: false
  except:
    - schedules
  environment:
    name: production
    url: http://$PRODUCTION_DOMAIN
  script:
    - npm install --global surge
    - surge --project ./public --domain $PRODUCTION_DOMAIN

test production:
  except:
    - schedules
  image: alpine
  stage: production tests
  cache: {}
  only:
    - master
  script:
    - apk add --no-cache curl
    - curl -s "https://michaelbruceallen.surge.sh" | grep -q "Hi people"
    - curl -s "https://michaelbruceallen.surge.sh" | grep -q "$CI_COMMIT_SHORT_SHA"
